Upgrade to latest poetry to fix CI
This should fix the bug that I'm seeing when running `poetry install`:

```
AttributeError

'HTTPResponse' object has no attribute 'strict'
                ),
                u"status": response.status,
                u"version": response.version,
                u"reason": text_type(response.reason),
                u"strict": response.strict,
                u"decode_content": response.decode_content,
            }
        }
```

The root cause has to do with changes in `urllib3` and `requests`, I
believe, but not going to expend too much effort working through
understanding it. We should run newer poetry *anyway*.